#!/usr/bin/env node
// Generate docs/STATUS.md from what the sibling checkouts actually declare.
//
// For each system this hub documents, read the package manifest in the
// sibling checkout (../flashy-ledger and so on, beside this repository) and
// record its declared name and version, plus the commit and branch that
// checkout is on. A checkout that is absent is reported as absent — never
// guessed, never carried over from a previous run.
//
// Deliberately NOT here: uptime, availability, latency, incident counts,
// test counts, coverage. Nothing in this repository measures any of those,
// so this file cannot honestly carry them. The version a checkout declares
// is also not evidence that any registry serves it.
//
// Dependency-free. Node 22, ESM. Regenerate with `npm run status`; the
// output is a generated file and is never hand-edited.

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { dirname, resolve, relative } from 'node:path'
import { spawnSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const SIBLINGS = resolve(ROOT, '..')
const OUT = resolve(ROOT, 'docs/STATUS.md')

/** The systems, where their checkout sits, and which manifest names the package. */
export const SYSTEMS = [
  { system: 'Ledger', checkout: 'flashy-ledger', manifest: 'package.json', page: 'api/ledger-api.md' },
  { system: 'Rails', checkout: 'flashy-rails', manifest: 'package.json', page: 'api/rails-api.md' },
  { system: 'Magician (core)', checkout: 'magician', manifest: 'packages/core/package.json', page: 'api/magician-api.md' },
  { system: 'FlashyID (SDK)', checkout: 'flashyid', manifest: 'packages/sdk/package.json', page: 'api/flashyid-api.md' },
  { system: 'Examples', checkout: 'flashy-examples', manifest: 'package.json', page: null },
]

const ABSENT = 'unknown — sibling checkout absent'

function git(dir, args) {
  const run = spawnSync('git', ['-C', dir, ...args], { encoding: 'utf8' })
  if (run.status !== 0) return null
  const out = run.stdout.trim()
  return out === '' ? null : out
}

export function readSystem(entry, siblings = SIBLINGS) {
  const dir = resolve(siblings, entry.checkout)
  const manifestPath = resolve(dir, entry.manifest)
  if (!existsSync(dir) || !existsSync(manifestPath)) {
    return { ...entry, present: false }
  }
  let name = 'unknown — manifest unreadable'
  let version = name
  try {
    const pkg = JSON.parse(readFileSync(manifestPath, 'utf8'))
    name = typeof pkg.name === 'string' ? pkg.name : 'unknown — manifest has no name'
    version = typeof pkg.version === 'string' ? pkg.version : 'unknown — manifest has no version'
  } catch { /* reported as unreadable above */ }
  return {
    ...entry,
    present: true,
    name,
    version,
    commit: git(dir, ['rev-parse', '--short', 'HEAD']) ?? 'unknown — not a git checkout',
    branch: git(dir, ['branch', '--show-current']) ?? 'detached',
  }
}

export function render(rows, measured) {
  const cell = (s) => String(s).replace(/\|/g, '\\|')
  const lines = [
    '# Status',
    '',
    '<!-- GENERATED by tools/status.mjs. Do not hand-edit; run `npm run status`. -->',
    '',
    `measured: ${measured}`,
    '',
    'What each sibling checkout declared when this file was generated. A row',
    'reads its package manifest and the commit the checkout was on; a checkout',
    'that was not present beside this repository is reported as absent rather',
    'than filled in from memory.',
    '',
    '| System | Package | Declared version | Commit | Branch | Reference |',
    '|---|---|---|---|---|---|',
  ]
  for (const r of rows) {
    const ref = r.page ? `[${r.page}](${r.page})` : '—'
    if (!r.present) {
      lines.push(`| ${cell(r.system)} | ${ABSENT} | ${ABSENT} | ${ABSENT} | ${ABSENT} | ${ref} |`)
    } else {
      lines.push(`| ${cell(r.system)} | \`${cell(r.name)}\` | ${cell(r.version)} | \`${cell(r.commit)}\` | \`${cell(r.branch)}\` | ${ref} |`)
    }
  }
  lines.push(
    '',
    '## What this file does not say',
    '',
    '- **No uptime, availability, latency or incident figures.** Nothing in this',
    '  repository measures a running service, so none is reported.',
    '- **A declared version is not a published one.** The version column is what',
    '  the checkout\'s manifest carries, not what any package registry serves.',
    '  [guides/setup-local.md](guides/setup-local.md) explains how to install from',
    '  the sibling checkouts instead.',
    '- **The commit is the checkout\'s, not the repository\'s default branch.** The',
    '  branch column says which branch was measured; read the ref before treating',
    '  a row as a statement about what ships.',
    '',
  )
  return lines.join('\n')
}

function main() {
  const measured = new Date().toISOString()
  const rows = SYSTEMS.map((s) => readSystem(s))
  writeFileSync(OUT, render(rows, measured))
  console.log(`status: wrote ${relative(ROOT, OUT)} (measured ${measured})`)
  for (const r of rows) {
    console.log(r.present
      ? `  ${r.system}: ${r.name}@${r.version} at ${r.commit} (${r.branch})`
      : `  ${r.system}: ${ABSENT}`)
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main()
